# @package _global_

# Env structure
simulator:
  _target_: humanoidverse.simulator.genesis.genesis.Genesis
  _recursive_: False
  config:
    name: "genesis"
    terrain: ${terrain}
    plane:
        static_friction: 1.0
        dynamic_friction: 1.0
        restitution: 0.0
    sim:
      fps: 200
      control_decimation: 4
      substeps: 1
      render_mode: "human" # [None, "human", "rgb_array"]
      render_interval: 1
    
    scene:
      num_envs: ${num_envs}
      env_spacing: ${env.config.env_spacing}
      replicate_physics: True