# @package _global_

env:
  _target_: humanoidverse.envs.base_task.base_task.BaseTask
  _recursive_: False
  config:
    experiment_name: ${experiment_name}
    num_envs: ${num_envs}
    headless: ${headless}
    simulator: ${simulator}
    save_rendering_dir: null
    ckpt_dir: null

# Globally accessible parameters
log_task_name: base_task