# @package _global_

defaults:
  - base_task

# Env structure
env:
  _target_: humanoidverse.envs.legged_base_task.legged_robot_base.LeggedRobotBase
  _recursive_: False
  config:
    robot: ${robot}
    domain_rand: ${domain_rand}
    rewards: ${rewards}
    terrain: ${terrain}
    obs: ${obs}
    env_spacing: 5.0
    max_episode_length_s: 20

    normalization:
      clip_actions: 100.0
      clip_observations: 100.0

    # simulator:
    #   sim:
    #     fps: 200 # 1/dt , dt = 0.005
    #     control_decimation: 4  # decimation
    #     substeps: 1
    termination:
      terminate_when_close_to_dof_pos_limit: False
      terminate_when_close_to_dof_vel_limit: False
      terminate_when_close_to_torque_limit: False
    termination_scales:
      termination_close_to_dof_pos_limit : 0.98
      termination_close_to_dof_vel_limit : 0.98
      termination_close_to_torque_limit : 0.98

# Globally accessible parameters
log_task_name: legged_base