# @package _global_

robot:
  # Observation parameters
  dof_obs_size: ???
  number_of_actions: ???
  self_obs_max_coords: ???
  num_bodies: ???

  # Control parameters
  # dof_body_ids: ???
  # dof_offsets: ???

  algo_obs_dim_dict: ???

  key_bodies: null
  contact_bodies: null

  foot_name: null

  init_state: null

  contact_pairs_multiplier: 16

  num_key_bodies: ${len:${robot.key_bodies}}
  mimic_small_marker_bodies: null

  randomize_link_body_names: ???

  control:
    # Can be "isaac_pd" or "P"/"V"/"T" for Proportional, Velocity, Torque control
    control_type: isaac_pd
    # PD Drive parameters:
    stiffness: null
    damping: null
    # action scale: target angle = actionScale * action + defaultAngle
    # only used in manual PD control
    action_scale: 1.0
    # Used with isaac pd controller
    isaac_pd_scale: False  # This is needed for the SMPL model due to weight variations
    clamp_actions: 1.0
    clip_torques: ???

  asset:
    collapse_fixed_joints: null
    replace_cylinder_with_capsule: null
    flip_visual_attachments: null
    armature: null
    thickness: null
    max_angular_velocity: null
    max_linear_velocity: null
    density: null
    angular_damping: null
    linear_damping: null
    disable_gravity: null
    fix_base_link: null
    default_dof_drive_mode: 1  # see GymDofDriveModeFlags (0 is none, 1 is pos tgt, 2 is vel tgt, 3 effort)

    robot_type: ???
    urdf_file: null
    usd_file: null
    xml_file: null
    asset_root: "humanoidverse/data/robots"
    self_collisions: True
    filter_ints: null

# motion_lib:
#   _target_: phys_anim.utils.motion_lib.MotionLib
#   motion_file: ${motion_file}
#   ref_height_adjust: 0.
#   fix_motion_heights: True
